### ISSUE TITLE
Update Javascript removing calls for .browser

### ISSUE THREAD

**Issue by amallory** [ivycat/IvyCat-AJAX-Testimonials#31]
Support for jQuery.browser http://api.jquery.com/jQuery.browser/ was removed in jQuery 1.9 installing the jQuery Migrate plugin https://wordpress.org/plugins/jquery-migrate/ will resolve this until the .js code is updated. if jQuery.fn.customFadeOut or FadeIn are called they check for jQuery.browser.msie which will fail. Line 82 and 90 of ivycat-testimonials-scripts.js

**Comment by amallory** [comment]
There isn't another way to test for IE's issues with fading at this time. The solution is to make the jQuery Migrate library a dependency for our script.

**Comment by sewmyheadon** [comment]
AJ, I've incorporated your pull request and plan to release the updates on .org pronto.
