### ISSUE TITLE
Plugin does not work with Wordpress version 4.5.2

### ISSUE THREAD

**Issue by twocatszerokarma** [ivycat/ivycat-ajax-testimonials#34]

**Comment by amallory** [comment]
Hello twocatszerokarma, I'm sorry you are having issue with the plugin. The Testimonials plugin does indeed work with WordPress 4.5.2. I would recommend you open a support ticket here: https://wordpress.org/support/plugin/ivycat-ajax-testimonials include some details of what isn't working for you.

**Comment by twocatszerokarma** [comment]
The shortcode does not work/doesn't get processed

**Comment by sewmyheadon** [comment]
Hello twocatszerokarma,

So far, we're not seeing an issue and have this plugin live on a lot of sites, including our own. It's likely that there's some sort of plugin or theme conflict going on.

Questions:

1. How long were you using the plugin before the issue occurred?
2. Did the issue surface immediately after updating to v. 4.5.2?
3. Have you tried troubleshooting by trying a default theme? Deactivating other plugins?
4. Can you provide the name of your theme and the list of plugins you're using?
5. Are you using any shortcode plugins?

Thanks!
